### ISSUE TITLE
shit src

### ISSUE THREAD

**Issue by TerikKek** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#12]
cirru fixed half of the shit u did nothing

**Comment by Hqrion** [comment]
You really do love me done you? From Discord to even GitHub. 🤪 Same as crystalinqq, we only allow “intellects” to open issues. Please do not create an issue again thanks, any new ones will be instantly discarded regardless. Ciruu is a good friend of mine, and he is experienced in this, he has been credited for the work he has done.
