### ISSUE TITLE
dude

### ISSUE THREAD

**Issue by lockerqqing** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#13]
Where is org and club folder? Its missing bruh

**Comment by Hqrion** [comment]
Hello, this will be looked at when I have time. If you want you can make a PR and it will be reviewed.

**Comment by ciruu1** [comment]
> Where is org and club folder? Its missing bruh

If you mean the mixins and discord RPC dependencies are included in build.gradle file

**Comment by ya-ilya** [comment]
^^^

**Comment by Hqrion** [comment]
Can I close this issue now or else there anything else I can help you with?
