### ISSUE TITLE
Please remove the fucking mixin that doesn't let the client run with other clients (also please make a new deobf this one has a ton of shit broken )

### ISSUE THREAD

**Issue by AiryXV** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#16]
the mixin is in minecraft isHittingBlockHook

**Comment by wyvest** [comment]
i think this is something the phobos devs have to fix.

**Comment by Hqrion** [comment]
> also please make a new deobf this one has a ton of shit broken )
A Procyon Decomp is coming soon.
