### ISSUE TITLE
soooo

### ISSUE THREAD

**Issue by lockerqqing** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#17]
there is a bug which makes the client lag, its about the custom main menu

**Comment by Hqrion** [comment]
Yes, 1.7.2 makes fps drop a lot.

**Comment by lockerqqing** [comment]
> Yes, 1.7.2 makes fps drop a lot.

Can you fix it please? Please :(

**Comment by Hqrion** [comment]
No ask phobos devs to fix it, or just get a good pc, or just simply remove the background code. 👍
