### ISSUE TITLE
outdated use gopros https://github.com/Gopro336/Phobos_1.7.2-BUILDABLE-SRC-Non-Chinese-

### ISSUE THREAD

**Issue by Cappinqq** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#18]
gopros works exactly like the original source
https://github.com/Gopro336/Phobos_1.7.2-BUILDABLE-SRC-Non-Chinese-

**Comment by Hqrion** [comment]
I think you are the issue here, I don’t care about a decompile source lol, I don’t fanboy Phobos like him.
