### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by YeahOMA** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#20]
I cloned the repo, did everything in order to get the project to set up in IntelliJ, I added cosmetics, ran ./gradlew build and used the built JAR and the game just crashes.

**Comment by Hqrion** [comment]
Did you do gradlew setupDecompWorkspace?

**Comment by Hqrion** [comment]
No reply, closing issue, please contact me via discord Hqrion#0090
