### ISSUE TITLE
Multiplayer dont work with other mods :((

### ISSUE THREAD

**Issue by MaxAdventures** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#28]
I have to use 1.3.3 right now because it don't want to work with other mods online 
Big sad maybe the next update they will fix.
 If there is a newer version that is not 1.7.2 and newer than 1.3.3 please send link
this is what it says (net/minecraft/network/nettyCompressionDecoder)

**Comment by Hqrion** [comment]
Ah, yeah that's a compatibility issue, I'll try do smth abt it idk
