### ISSUE TITLE
Rat found

### ISSUE THREAD

**Issue by badcodehash** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#31]
Rat at https://github.com/Hqrion/Phobos-1.7.2-BUILDABLE-SRC/blob/main/src/main/java/me/earth/phobos/util/TextUtil.java

**Comment by badcodehash** [comment]
update: nevermind. It seems like phobos developers wanted to troll someone. Sorry for inconvenience. Upon decoding "pword" you get
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 ███▒█▒█▒███▒███▒███▒███
 █▒█▒█▒█▒█▒█▒█▒█▒█▒█▒█▒▒
 ███▒███▒█▒█▒███▒█▒█▒███
 █▒▒▒█▒█▒█▒█▒█▒█▒█▒█▒▒▒█
 █▒▒▒█▒█▒███▒███▒███▒███
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒

**Comment by Hqrion** [comment]
Ok, no problem
