### ISSUE TITLE
very bad

### ISSUE THREAD

**Issue by Crystallinqq** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#4]
old cfr troll, decompiling dependencies??, leaving in the cfr shit at the top. very cringe and hard to look at. please fix this.

**Comment by Hqrion** [comment]
Sorry, we only allow “intellects” to create issues. Please do not create an issue again.

**Comment by leKamikaze1** [comment]
LMAO, HE IS ONE OF THE PEOPLE THAT MADE THE CLIENT, YOU FUCKING IDIOT

**Comment by FerrumTheElement** [comment]
> LMAO, HE IS ONE OF THE PEOPLE THAT MADE THE CLIENT, YOU FUCKING IDIOT

i think he knows YOU FUCKING IDIOT

**Comment by justvurce** [comment]
> > LMAO, HE IS ONE OF THE PEOPLE THAT MADE THE CLIENT, YOU FUCKING IDIOT
> 
> i think he knows YOU FUCKING IDIOT

HAHA CAPS LOCK

**Comment by Boba235** [comment]
faggots

**Comment by Hqrion** [comment]
commenting on an issue from 2020 🥱
