### ISSUE TITLE
Replace the discord RPC binaries with the official ones

### ISSUE THREAD

**Issue by zyktex** [Hqrion/Phobos-1.7.2-BUILDABLE-SRC#9]
Afaik the discord RPC binaries have not been checked, and that's most likely where any potential malware would be. Replacing the binaries with the official ones (https://github.com/MinnDevelopment/discord-rpc-release) would ensure that there is no malware in the binaries.

**Comment by Hqrion** [comment]
Hello, I'll look into this.

**Comment by Hqrion** [comment]
Binaries have now been replaced with the official ones, hope this helps, thanks.
